// <auto-generated />
using System;
using AkilliKomponentStokAsistani.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AkilliKomponentStokAsistani.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("AkilliKomponentStokAsistani.Web.Models.ComponentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatasheetUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumStockLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ComponentItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Resistor",
                            ComponentName = "1k Ohm Resistor",
                            CreatedAt = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatasheetUrl = "http://example.com/1k-resistor",
                            Description = "Standard 1k Ohm resistor",
                            MinimumStockLevel = 20,
                            PackageType = "Axial",
                            Price = 0.10m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Category = "Capacitor",
                            ComponentName = "10uF Capacitor",
                            CreatedAt = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatasheetUrl = "http://example.com/10uf-capacitor",
                            Description = "Electrolytic capacitor",
                            MinimumStockLevel = 15,
                            PackageType = "Radial",
                            Price = 0.15m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 3,
                            Category = "Microcontroller",
                            ComponentName = "STM32F103C8T6",
                            CreatedAt = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatasheetUrl = "http://example.com/stm32f103",
                            Description = "ARM Cortex-M3 microcontroller",
                            MinimumStockLevel = 10,
                            PackageType = "LQFP",
                            Price = 2.50m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 4,
                            Category = "Transistor",
                            ComponentName = "BC547 Transistor",
                            CreatedAt = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatasheetUrl = "http://example.com/bc547",
                            Description = "NPN transistor",
                            MinimumStockLevel = 50,
                            PackageType = "TO-92",
                            Price = 0.05m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 5,
                            Category = "Voltage Regulator",
                            ComponentName = "LM7805 Voltage Regulator",
                            CreatedAt = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatasheetUrl = "http://example.com/lm7805",
                            Description = "5V voltage regulator",
                            MinimumStockLevel = 10,
                            PackageType = "TO-220",
                            Price = 0.75m,
                            StockQuantity = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
